services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:28aeeb61994af3076a1cf58ab29f728b936381698b191e69b2183f5aa3e23b75
      repository: armory/e2e-extension-service
      tag: 2021.09.01.16.59.00.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: 1b8b25a0f134b5f5a19741d7e4e8f54fc79394f7
