services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:e4ccf799f9fc724a1df1244de2664b7c3a6ab90ee7b6bbd1502e5323d1fd90a5
      repository: armory/e2e-extension-service
      tag: 2021.08.02.23.06.05.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: b18861831e5db5f33e816be8fad38db903345a3c
