services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:c6aa17af9dc511f3c405b0ec323772fecb5ef965b26f52b9ec753acef882eed4
      repository: armory/e2e-extension-service
      tag: 2021.07.30.16.40.58.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: fd1998b62d0418f1375e4cd5a41faa58d70a54c9
