services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:2719f2f6cd1615b04d030612c37e30b4893bef902a705a01a9208f3f49a37ef5
      repository: armory/e2e-extension-service
      tag: 2022.01.03.23.40.36.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: 8ddc8c208fce889a861c64fd9a65b441fb42a19a
