services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:2e1b7b8829be208cf42998d9e5cbf14e7bee4b0d332584bbeb7ac843a25c32d7
      repository: armory/e2e-extension-service
      tag: 2021.08.01.14.25.33.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: 879d353ed35865240366b22e7bcdc2ea496d74c1
