services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:d1b001dac9b62c1ced7961b0eb6f0349db67aa122f9000f00418d700d9c116f7
      repository: armory/e2e-extension-service
      tag: 2021.11.11.23.39.22.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: 78159f5c5552775206031bd9f69e0afdb1f2abdb
