services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:5fe33f30806f9ddc55a1bea7f858159c9790676e2c8e409626c64102fb779ee3
      repository: armory/e2e-extension-service
      tag: 2021.07.30.16.45.15.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: 381520e8803b552f5d84cc158b5dd40fb9f28996
