services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:c5e2507ec3fa0156441f4650e85fc0f80889a93e783b93b54b3bc2f4e2315129
      repository: armory/e2e-extension-service
      tag: 2022.03.03.22.22.56.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: 6a392652cb72b58c32cf118d09f95d41f7afb171
