services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:76f0f73f108e9b7641318841003d4ca19a7eaebec1a38816867f23383642dcc4
      repository: armory/e2e-extension-service
      tag: 2021.07.30.16.59.50.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: 9c5388fd18d479d4de3804c01cf3b78958342217
