services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:3a2d5281ffcbe55786839051a2604185d61ce1de682edb49a0f41b403db75cf7
      repository: armory/e2e-extension-service
      tag: 2021.08.02.23.10.06.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: 3dc1c35693a8778f7d88eb7002c19a94b2e73894
