services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:7ad34460bfe4431175d29fc658e7aa4ac08f3b14d4bbb8b354b63c8784cf9870
      repository: armory/e2e-extension-service
      tag: 2021.08.01.02.07.14.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: c719bf11c28ebd82944b0702997c8dfc720e2b46
