services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:1ecd46811452794a692a7a148749bf8d7e7017b09cd670c8490600482abe9339
      repository: armory/e2e-extension-service
      tag: 2022.03.08.21.59.22.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: 8fc733470cade849dd4b533d4572a3b5eefc4b53
