services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:70c5d8ee916543e10fc2dfda5f432e93d87ce94f00a141f0c3ecf79dede2e9e1
      repository: armory/e2e-extension-service
      tag: 2022.08.17.03.03.23.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: e98a6ebb805b9d5228f2361cd9484f3858811833
