services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:376def7c7618462b1338eaa5e4c1acab406fdfaa2dceb4bd4893c0267400c936
      repository: armory/e2e-extension-service
      tag: 2021.08.01.03.20.46.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: f18446683579719400d710970fb00a5ba3139b68
