services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:b535af54ea88ec87da9563b9e8954d314a10ae940a5e89fba8ad7c40acf00fe8
      repository: armory/e2e-extension-service
      tag: 2021.08.30.22.43.52.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: aa3296af1320c514147c6a4166cc599f81e85d83
