services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:5d409c6e8b09db76e75b7b693b4154f591823a4ec3c203204dd6ed5e5fe322d9
      repository: armory/e2e-extension-service
      tag: 2021.08.04.19.37.41.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: a44ad65b6ac1216742466c46ac0cd742218e0026
