services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:515420b896eb4fe6596b35c16661bc2f9666ba6c8380526e0548acb811c467f9
      repository: armory/e2e-extension-service
      tag: 2021.11.10.15.57.48.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: 8cfbc69d82ced1fd4a887373eb93389c892c3b62
