services:
  e2e-extension-service:
    baseService: e2e-oss-service
    image:
      imageId: sha256:1091137eba5eed955b5e5e68f4d71125e8e7ff515c9e2b14353c2b6243adacdd
      repository: armory/e2e-extension-service
      tag: 2021.12.06.21.53.21.main
    vcs:
      repo:
        orgName: armory-io
        repoName: e2e-extension-service
        type: github
      sha: 617ae2a33452f058a3c81d306c88db3e39610d0f
